package com.example.artsphere.ui

/**
 * Modele danych dla paneli statystyk
 */

// ========== ADMIN STATISTICS ==========
data class AdminStatistics(
    val totalUsers: Int,
    val totalSellers: Int,
    val totalBuyers: Int,
    val totalTransactionValue: Double,
    val averageOrderValue: Double,
    val newUsersThisMonth: Int,
    val totalArtworks: Int,
    val activeListings: Int,
    val completedOrders: Int,
    val pendingOrders: Int
)

// ========== SELLER STATISTICS ==========
data class SellerStatistics(
    val totalSales: Int,
    val totalRevenue: Double,
    val averageRating: Float,
    val followerCount: Int,
    val totalArtworks: Int,
    val activeListings: Int,
    val soldThisMonth: Int,
    val revenueThisMonth: Double,
    val topArtworkTitle: String,
    val topArtworkSales: Int,
    val pendingOrders: Int,
    val completedOrders: Int
)

// ========== CLIENT STATISTICS ==========
data class ClientStatistics(
    val totalSpent: Double,
    val totalPurchases: Int,
    val favoriteArtistsCount: Int,
    val wishlistCount: Int,
    val reviewsGiven: Int,
    val averageRating: Float,
    val spentThisMonth: Double,
    val purchasesThisMonth: Int,
    val memberSince: String,
    val savedArtworks: Int
)

// ========== USER MANAGEMENT ==========
data class UserInfo(
    val id: Long,
    val username: String,
    val email: String,
    val firstName: String,
    val lastName: String,
    val role: String, // "BUYER", "SELLER", "ADMIN"
    val balance: Double,
    val registrationDate: String,
    val isActive: Boolean = true,
    val lastLogin: String? = null
)

// ========== ARTWORK MANAGEMENT ==========
data class ArtworkInfo(
    val id: Long,
    val title: String,
    val artist: String?,
    val description: String?,
    val price: Double?,
    val isPriceless: Boolean,
    val category: String?,
    val imagePath: String?,
    val width: Double?,
    val height: Double?,
    val depth: Double?,
    val sellerId: Long,
    val sellerUsername: String,
    val isSold: Boolean,
    val status: String, // "AVAILABLE", "SOLD", "HIDDEN"
    val createdAt: String,
    val views: Int = 0
)

// ========== SELLER MANAGEMENT ==========
data class SellerInfo(
    val id: Long,
    val username: String,
    val email: String,
    val firstName: String,
    val lastName: String,
    val balance: Double,
    val registrationDate: String,
    val isActive: Boolean = true,
    val lastLogin: String? = null,
    // Statystyki sprzedawcy
    val totalArtworks: Int,
    val soldArtworks: Int,
    val activeArtworks: Int,
    val totalRevenue: Double,
    val followerCount: Int,
    val averageRating: Float,
    val isVerified: Boolean = false
)

// ========== ORDER MANAGEMENT ==========
data class OrderInfo(
    val id: Long,
    val orderNumber: String,
    val buyerId: Long,
    val buyerName: String,
    val buyerEmail: String,
    val sellerId: Long,
    val sellerName: String,
    val artworkId: Long,
    val artworkTitle: String,
    val artworkImage: String?,
    val quantity: Int,
    val unitPrice: Double,
    val totalAmount: Double,
    val status: String, // "PENDING", "PROCESSING", "SHIPPED", "DELIVERED", "CANCELLED"
    val orderDate: String,
    val paymentMethod: String,
    val paymentStatus: String, // "PAID", "PENDING", "REFUNDED"
    val shippingAddress: String,
    val shippingCity: String,
    val shippingPostalCode: String,
    val shippingCountry: String,
    val trackingNumber: String?,
    val estimatedDelivery: String?,
    val actualDelivery: String?,
    val notes: String?
)

// ========== CATEGORY MANAGEMENT ==========
data class CategoryInfo(
    val id: Long,
    val name: String,
    val description: String,
    val slug: String,
    val parentId: Long?,
    val parentName: String?,
    val isActive: Boolean,
    val artworkCount: Int,
    val createdDate: String,
    val lastModified: String,
    val displayOrder: Int,
    val iconName: String?,
    val color: String?
)

// ========== MOCK DATA PROVIDER ==========
object MockStatisticsProvider {
    
    fun getAdminStatistics(): AdminStatistics {
        return AdminStatistics(
            totalUsers = 1247,
            totalSellers = 156,
            totalBuyers = 1091,
            totalTransactionValue = 284750.50,
            averageOrderValue = 450.25,
            newUsersThisMonth = 87,
            totalArtworks = 3456,
            activeListings = 2341,
            completedOrders = 632,
            pendingOrders = 45
        )
    }
    
    fun getMockUsers(): List<UserInfo> {
        return listOf(
            UserInfo(
                id = 1,
                username = "jankowalski",
                email = "jan.kowalski@example.com",
                firstName = "Jan",
                lastName = "Kowalski",
                role = "BUYER",
                balance = 2500.00,
                registrationDate = "15.01.2024",
                isActive = true,
                lastLogin = "27.03.2026 18:15"
            ),
            UserInfo(
                id = 2,
                username = "anna_nowak",
                email = "anna.nowak@example.com",
                firstName = "Anna",
                lastName = "Nowak",
                role = "SELLER",
                balance = 15680.50,
                registrationDate = "22.01.2024",
                isActive = true,
                lastLogin = "27.03.2026 14:30"
            ),
            UserInfo(
                id = 3,
                username = "piotr_wisniewski",
                email = "piotr.wisniewski@example.com",
                firstName = "Piotr",
                lastName = "Wiśniewski",
                role = "SELLER",
                balance = 8420.00,
                registrationDate = "05.02.2024",
                isActive = true,
                lastLogin = "26.03.2026 20:45"
            ),
            UserInfo(
                id = 4,
                username = "maria_kowalczyk",
                email = "maria.kowalczyk@example.com",
                firstName = "Maria",
                lastName = "Kowalczyk",
                role = "BUYER",
                balance = 1200.00,
                registrationDate = "10.02.2024",
                isActive = true,
                lastLogin = "27.03.2026 10:20"
            ),
            UserInfo(
                id = 5,
                username = "tomasz_lewandowski",
                email = "tomasz.lew@example.com",
                firstName = "Tomasz",
                lastName = "Lewandowski",
                role = "BUYER",
                balance = 3450.00,
                registrationDate = "18.02.2024",
                isActive = false,
                lastLogin = "15.03.2026 16:30"
            ),
            UserInfo(
                id = 6,
                username = "katarzyna_wojcik",
                email = "k.wojcik@example.com",
                firstName = "Katarzyna",
                lastName = "Wójcik",
                role = "SELLER",
                balance = 22100.00,
                registrationDate = "25.02.2024",
                isActive = true,
                lastLogin = "27.03.2026 17:00"
            ),
            UserInfo(
                id = 7,
                username = "andrzej_kaminski",
                email = "andrzej.k@example.com",
                firstName = "Andrzej",
                lastName = "Kamiński",
                role = "BUYER",
                balance = 890.00,
                registrationDate = "03.03.2024",
                isActive = true,
                lastLogin = "25.03.2026 12:15"
            ),
            UserInfo(
                id = 8,
                username = "magdalena_zielinska",
                email = "m.zielinska@example.com",
                firstName = "Magdalena",
                lastName = "Zielińska",
                role = "SELLER",
                balance = 11250.00,
                registrationDate = "08.03.2024",
                isActive = true,
                lastLogin = "27.03.2026 09:45"
            ),
            UserInfo(
                id = 9,
                username = "krzysztof_szymanski",
                email = "k.szymanski@example.com",
                firstName = "Krzysztof",
                lastName = "Szymański",
                role = "BUYER",
                balance = 4200.00,
                registrationDate = "15.03.2024",
                isActive = true,
                lastLogin = "27.03.2026 11:30"
            ),
            UserInfo(
                id = 10,
                username = "joanna_wozniak",
                email = "joanna.w@example.com",
                firstName = "Joanna",
                lastName = "Woźniak",
                role = "BUYER",
                balance = 1850.00,
                registrationDate = "20.03.2024",
                isActive = true,
                lastLogin = "26.03.2026 19:20"
            ),
            UserInfo(
                id = 11,
                username = "marek_kozlowski",
                email = "marek.kozlowski@example.com",
                firstName = "Marek",
                lastName = "Kozłowski",
                role = "SELLER",
                balance = 18900.00,
                registrationDate = "22.03.2024",
                isActive = true,
                lastLogin = "27.03.2026 15:50"
            ),
            UserInfo(
                id = 12,
                username = "ewa_jankowska",
                email = "ewa.jankowska@example.com",
                firstName = "Ewa",
                lastName = "Jankowska",
                role = "ADMIN",
                balance = 0.00,
                registrationDate = "01.01.2024",
                isActive = true,
                lastLogin = "27.03.2026 18:00"
            )
        )
    }
    
    fun getMockArtworks(): List<ArtworkInfo> {
        return listOf(
            ArtworkInfo(
                id = 1,
                title = "Zachód słońca nad morzem",
                artist = "Anna Nowak",
                description = "Piękny pejzaż morski przedstawiający zachód słońca. Dzieło wykonane farbami olejnymi na płótnie.",
                price = 1500.00,
                isPriceless = false,
                category = "Malarstwo",
                imagePath = "/images/artworks/sunset.jpg",
                width = 60.0,
                height = 40.0,
                depth = 3.0,
                sellerId = 2,
                sellerUsername = "anna_nowak",
                isSold = false,
                status = "AVAILABLE",
                createdAt = "22.01.2024",
                views = 234
            ),
            ArtworkInfo(
                id = 2,
                title = "Portret kobiety w kapeluszu",
                artist = "Piotr Wiśniewski",
                description = "Ekspresyjny portret wykonany w stylu impresjonistycznym.",
                price = 850.00,
                isPriceless = false,
                category = "Malarstwo",
                imagePath = "/images/artworks/portrait.jpg",
                width = 35.0,
                height = 50.0,
                depth = 2.0,
                sellerId = 3,
                sellerUsername = "piotr_wisniewski",
                isSold = false,
                status = "AVAILABLE",
                createdAt = "05.02.2024",
                views = 187
            ),
            ArtworkInfo(
                id = 3,
                title = "Abstrakcja w błękicie",
                artist = "Katarzyna Wójcik",
                description = "Nowoczesna abstrakcja z dominującymi odcieniami błękitu i złota.",
                price = null,
                isPriceless = true,
                category = "Sztuka współczesna",
                imagePath = "/images/artworks/abstract.jpg",
                width = 80.0,
                height = 60.0,
                depth = 4.0,
                sellerId = 6,
                sellerUsername = "katarzyna_wojcik",
                isSold = false,
                status = "AVAILABLE",
                createdAt = "25.02.2024",
                views = 456
            ),
            ArtworkInfo(
                id = 4,
                title = "Miejski pejzaż nocą",
                artist = "Magdalena Zielińska",
                description = "Nocny widok na miasto z lotu ptaka. Gra świateł i cieni.",
                price = 1800.00,
                isPriceless = false,
                category = "Fotografia",
                imagePath = "/images/artworks/citynight.jpg",
                width = 70.0,
                height = 50.0,
                depth = 1.0,
                sellerId = 8,
                sellerUsername = "magdalena_zielinska",
                isSold = true,
                status = "SOLD",
                createdAt = "08.03.2024",
                views = 312
            ),
            ArtworkInfo(
                id = 5,
                title = "Rzeźba \"Harmonia\"",
                artist = "Marek Kozłowski",
                description = "Współczesna rzeźba z brązu przedstawiająca zrównoważone formy.",
                price = 4500.00,
                isPriceless = false,
                category = "Rzeźba",
                imagePath = "/images/artworks/sculpture.jpg",
                width = 30.0,
                height = 45.0,
                depth = 30.0,
                sellerId = 11,
                sellerUsername = "marek_kozlowski",
                isSold = false,
                status = "AVAILABLE",
                createdAt = "22.03.2024",
                views = 89
            ),
            ArtworkInfo(
                id = 6,
                title = "Kwiaty w wazonie",
                artist = "Anna Nowak",
                description = "Martwa natura z bukietem polnych kwiatów.",
                price = 650.00,
                isPriceless = false,
                category = "Malarstwo",
                imagePath = "/images/artworks/flowers.jpg",
                width = 40.0,
                height = 50.0,
                depth = 2.0,
                sellerId = 2,
                sellerUsername = "anna_nowak",
                isSold = false,
                status = "AVAILABLE",
                createdAt = "10.02.2024",
                views = 156
            ),
            ArtworkInfo(
                id = 7,
                title = "Górski krajobraz",
                artist = "Piotr Wiśniewski",
                description = "Widok na Tatry o wschodzie słońca.",
                price = 2200.00,
                isPriceless = false,
                category = "Malarstwo",
                imagePath = "/images/artworks/mountains.jpg",
                width = 90.0,
                height = 60.0,
                depth = 3.0,
                sellerId = 3,
                sellerUsername = "piotr_wisniewski",
                isSold = true,
                status = "SOLD",
                createdAt = "15.02.2024",
                views = 567
            ),
            ArtworkInfo(
                id = 8,
                title = "Minimalizm #3",
                artist = "Katarzyna Wójcik",
                description = "Minimalistyczna kompozycja geometryczna.",
                price = 980.00,
                isPriceless = false,
                category = "Sztuka współczesna",
                imagePath = "/images/artworks/minimal.jpg",
                width = 50.0,
                height = 50.0,
                depth = 2.0,
                sellerId = 6,
                sellerUsername = "katarzyna_wojcik",
                isSold = false,
                status = "AVAILABLE",
                createdAt = "01.03.2024",
                views = 201
            ),
            ArtworkInfo(
                id = 9,
                title = "Portret starej kobiety",
                artist = "Magdalena Zielińska",
                description = "Czarno-biała fotografia portretowa.",
                price = 450.00,
                isPriceless = false,
                category = "Fotografia",
                imagePath = "/images/artworks/oldwoman.jpg",
                width = 30.0,
                height = 40.0,
                depth = 1.0,
                sellerId = 8,
                sellerUsername = "magdalena_zielinska",
                isSold = false,
                status = "AVAILABLE",
                createdAt = "12.03.2024",
                views = 128
            ),
            ArtworkInfo(
                id = 10,
                title = "Taniec formy",
                artist = "Marek Kozłowski",
                description = "Dynamiczna rzeźba przedstawiająca ruch.",
                price = null,
                isPriceless = true,
                category = "Rzeźba",
                imagePath = "/images/artworks/dance.jpg",
                width = 25.0,
                height = 60.0,
                depth = 25.0,
                sellerId = 11,
                sellerUsername = "marek_kozlowski",
                isSold = false,
                status = "AVAILABLE",
                createdAt = "25.03.2024",
                views = 67
            ),
            ArtworkInfo(
                id = 11,
                title = "Jesienne liście",
                artist = "Anna Nowak",
                description = "Kolorowa kompozycja z jesiennych liści.",
                price = 720.00,
                isPriceless = false,
                category = "Malarstwo",
                imagePath = "/images/artworks/autumn.jpg",
                width = 45.0,
                height = 35.0,
                depth = 2.0,
                sellerId = 2,
                sellerUsername = "anna_nowak",
                isSold = false,
                status = "HIDDEN",
                createdAt = "05.03.2024",
                views = 43
            ),
            ArtworkInfo(
                id = 12,
                title = "Architektura brutalna",
                artist = "Piotr Wiśniewski",
                description = "Fotografia modernistycznej architektury.",
                price = 890.00,
                isPriceless = false,
                category = "Fotografia",
                imagePath = "/images/artworks/architecture.jpg",
                width = 60.0,
                height = 40.0,
                depth = 1.0,
                sellerId = 3,
                sellerUsername = "piotr_wisniewski",
                isSold = false,
                status = "AVAILABLE",
                createdAt = "18.03.2024",
                views = 178
            )
        )
    }
    
    fun getSellerStatistics(): SellerStatistics {
        return SellerStatistics(
            totalSales = 127,
            totalRevenue = 45680.00,
            averageRating = 4.7f,
            followerCount = 234,
            totalArtworks = 52,
            activeListings = 28,
            soldThisMonth = 12,
            revenueThisMonth = 5240.00,
            topArtworkTitle = "Zachód słońca nad jeziorem",
            topArtworkSales = 15,
            pendingOrders = 3,
            completedOrders = 124
        )
    }
    
    fun getClientStatistics(): ClientStatistics {
        return ClientStatistics(
            totalSpent = 8450.00,
            totalPurchases = 23,
            favoriteArtistsCount = 12,
            wishlistCount = 18,
            reviewsGiven = 19,
            averageRating = 4.5f,
            spentThisMonth = 1200.00,
            purchasesThisMonth = 3,
            memberSince = "Styczeń 2024",
            savedArtworks = 34
        )
    }
    
    fun getMockSellers(): List<SellerInfo> {
        return listOf(
            SellerInfo(
                id = 2,
                username = "anna_nowak",
                email = "anna.nowak@example.com",
                firstName = "Anna",
                lastName = "Nowak",
                balance = 15680.50,
                registrationDate = "22.01.2024",
                isActive = true,
                lastLogin = "27.03.2026 14:30",
                totalArtworks = 8,
                soldArtworks = 4,
                activeArtworks = 4,
                totalRevenue = 6370.00,
                followerCount = 87,
                averageRating = 4.7f,
                isVerified = true
            ),
            SellerInfo(
                id = 3,
                username = "piotr_wisniewski",
                email = "piotr.wisniewski@example.com",
                firstName = "Piotr",
                lastName = "Wiśniewski",
                balance = 8420.00,
                registrationDate = "05.02.2024",
                isActive = true,
                lastLogin = "26.03.2026 20:45",
                totalArtworks = 5,
                soldArtworks = 2,
                activeArtworks = 3,
                totalRevenue = 4850.00,
                followerCount = 45,
                averageRating = 4.3f,
                isVerified = true
            ),
            SellerInfo(
                id = 6,
                username = "katarzyna_wojcik",
                email = "k.wojcik@example.com",
                firstName = "Katarzyna",
                lastName = "Wójcik",
                balance = 22100.00,
                registrationDate = "25.02.2024",
                isActive = true,
                lastLogin = "27.03.2026 17:00",
                totalArtworks = 12,
                soldArtworks = 5,
                activeArtworks = 7,
                totalRevenue = 12450.00,
                followerCount = 156,
                averageRating = 4.9f,
                isVerified = true
            ),
            SellerInfo(
                id = 8,
                username = "magdalena_zielinska",
                email = "m.zielinska@example.com",
                firstName = "Magdalena",
                lastName = "Zielińska",
                balance = 11250.00,
                registrationDate = "08.03.2024",
                isActive = true,
                lastLogin = "27.03.2026 09:45",
                totalArtworks = 6,
                soldArtworks = 3,
                activeArtworks = 3,
                totalRevenue = 4050.00,
                followerCount = 62,
                averageRating = 4.5f,
                isVerified = true
            ),
            SellerInfo(
                id = 11,
                username = "marek_kozlowski",
                email = "marek.kozlowski@example.com",
                firstName = "Marek",
                lastName = "Kozłowski",
                balance = 18900.00,
                registrationDate = "22.03.2024",
                isActive = true,
                lastLogin = "27.03.2026 15:50",
                totalArtworks = 4,
                soldArtworks = 1,
                activeArtworks = 3,
                totalRevenue = 7500.00,
                followerCount = 34,
                averageRating = 4.8f,
                isVerified = false
            ),
            SellerInfo(
                id = 13,
                username = "jan_kowalczyk",
                email = "jan.kowal@example.com",
                firstName = "Jan",
                lastName = "Kowalczyk",
                balance = 3200.00,
                registrationDate = "10.03.2024",
                isActive = false,
                lastLogin = "12.03.2026 11:20",
                totalArtworks = 2,
                soldArtworks = 0,
                activeArtworks = 2,
                totalRevenue = 0.00,
                followerCount = 8,
                averageRating = 0.0f,
                isVerified = false
            )
        )
    }
    
    fun getMockOrders(): List<OrderInfo> {
        return listOf(
            OrderInfo(
                id = 1,
                orderNumber = "ORD-2026-001234",
                buyerId = 1,
                buyerName = "Jan Kowalski",
                buyerEmail = "jan.kowalski@example.com",
                sellerId = 2,
                sellerName = "Anna Nowak",
                artworkId = 101,
                artworkTitle = "Zachód słońca nad morzem",
                artworkImage = null,
                quantity = 1,
                unitPrice = 2500.00,
                totalAmount = 2500.00,
                status = "DELIVERED",
                orderDate = "15.03.2026",
                paymentMethod = "Karta kredytowa",
                paymentStatus = "PAID",
                shippingAddress = "ul. Kwiatowa 15/23",
                shippingCity = "Warszawa",
                shippingPostalCode = "00-001",
                shippingCountry = "Polska",
                trackingNumber = "PL123456789",
                estimatedDelivery = "20.03.2026",
                actualDelivery = "19.03.2026",
                notes = null
            ),
            OrderInfo(
                id = 2,
                orderNumber = "ORD-2026-001235",
                buyerId = 3,
                buyerName = "Maria Wiśniewska",
                buyerEmail = "maria.wisniewska@example.com",
                sellerId = 5,
                sellerName = "Tomasz Wójcik",
                artworkId = 102,
                artworkTitle = "Portret kobiety",
                artworkImage = null,
                quantity = 1,
                unitPrice = 3500.00,
                totalAmount = 3500.00,
                status = "SHIPPED",
                orderDate = "22.03.2026",
                paymentMethod = "Przelew bankowy",
                paymentStatus = "PAID",
                shippingAddress = "ul. Słoneczna 8",
                shippingCity = "Kraków",
                shippingPostalCode = "30-001",
                shippingCountry = "Polska",
                trackingNumber = "PL987654321",
                estimatedDelivery = "28.03.2026",
                actualDelivery = null,
                notes = "Proszę o ostrożne pakowanie"
            ),
            OrderInfo(
                id = 3,
                orderNumber = "ORD-2026-001236",
                buyerId = 4,
                buyerName = "Piotr Kamiński",
                buyerEmail = "piotr.kaminski@example.com",
                sellerId = 2,
                sellerName = "Anna Nowak",
                artworkId = 103,
                artworkTitle = "Abstrakcja geometryczna",
                artworkImage = null,
                quantity = 1,
                unitPrice = 1800.00,
                totalAmount = 1800.00,
                status = "PROCESSING",
                orderDate = "25.03.2026",
                paymentMethod = "BLIK",
                paymentStatus = "PAID",
                shippingAddress = "ul. Parkowa 45",
                shippingCity = "Wrocław",
                shippingPostalCode = "50-001",
                shippingCountry = "Polska",
                trackingNumber = null,
                estimatedDelivery = "30.03.2026",
                actualDelivery = null,
                notes = null
            ),
            OrderInfo(
                id = 4,
                orderNumber = "ORD-2026-001237",
                buyerId = 6,
                buyerName = "Katarzyna Lewandowska",
                buyerEmail = "k.lewandowska@example.com",
                sellerId = 7,
                sellerName = "Piotr Szymański",
                artworkId = 104,
                artworkTitle = "Górski krajobraz",
                artworkImage = null,
                quantity = 1,
                unitPrice = 4200.00,
                totalAmount = 4200.00,
                status = "PENDING",
                orderDate = "26.03.2026",
                paymentMethod = "Karta kredytowa",
                paymentStatus = "PENDING",
                shippingAddress = "ul. Leśna 12",
                shippingCity = "Poznań",
                shippingPostalCode = "60-001",
                shippingCountry = "Polska",
                trackingNumber = null,
                estimatedDelivery = "02.04.2026",
                actualDelivery = null,
                notes = "Proszę o kontakt przed dostawą"
            ),
            OrderInfo(
                id = 5,
                orderNumber = "ORD-2026-001238",
                buyerId = 1,
                buyerName = "Jan Kowalski",
                buyerEmail = "jan.kowalski@example.com",
                sellerId = 8,
                sellerName = "Magdalena Zielińska",
                artworkId = 105,
                artworkTitle = "Nowoczesna rzeźba",
                artworkImage = null,
                quantity = 1,
                unitPrice = 5500.00,
                totalAmount = 5500.00,
                status = "DELIVERED",
                orderDate = "10.03.2026",
                paymentMethod = "Przelew bankowy",
                paymentStatus = "PAID",
                shippingAddress = "ul. Kwiatowa 15/23",
                shippingCity = "Warszawa",
                shippingPostalCode = "00-001",
                shippingCountry = "Polska",
                trackingNumber = "PL555666777",
                estimatedDelivery = "17.03.2026",
                actualDelivery = "16.03.2026",
                notes = null
            ),
            OrderInfo(
                id = 6,
                orderNumber = "ORD-2026-001239",
                buyerId = 9,
                buyerName = "Agnieszka Dąbrowska",
                buyerEmail = "a.dabrowska@example.com",
                sellerId = 2,
                sellerName = "Anna Nowak",
                artworkId = 106,
                artworkTitle = "Martwa natura",
                artworkImage = null,
                quantity = 1,
                unitPrice = 1200.00,
                totalAmount = 1200.00,
                status = "CANCELLED",
                orderDate = "18.03.2026",
                paymentMethod = "Karta kredytowa",
                paymentStatus = "REFUNDED",
                shippingAddress = "ul. Ogrodowa 33",
                shippingCity = "Gdańsk",
                shippingPostalCode = "80-001",
                shippingCountry = "Polska",
                trackingNumber = null,
                estimatedDelivery = null,
                actualDelivery = null,
                notes = "Zmiana decyzji kupującego"
            ),
            OrderInfo(
                id = 7,
                orderNumber = "ORD-2026-001240",
                buyerId = 3,
                buyerName = "Maria Wiśniewska",
                buyerEmail = "maria.wisniewska@example.com",
                sellerId = 7,
                sellerName = "Piotr Szymański",
                artworkId = 107,
                artworkTitle = "Portret starszego mężczyzny",
                artworkImage = null,
                quantity = 1,
                unitPrice = 2800.00,
                totalAmount = 2800.00,
                status = "PROCESSING",
                orderDate = "24.03.2026",
                paymentMethod = "BLIK",
                paymentStatus = "PAID",
                shippingAddress = "ul. Słoneczna 8",
                shippingCity = "Kraków",
                shippingPostalCode = "30-001",
                shippingCountry = "Polska",
                trackingNumber = null,
                estimatedDelivery = "29.03.2026",
                actualDelivery = null,
                notes = null
            ),
            OrderInfo(
                id = 8,
                orderNumber = "ORD-2026-001241",
                buyerId = 10,
                buyerName = "Robert Jankowski",
                buyerEmail = "r.jankowski@example.com",
                sellerId = 5,
                sellerName = "Tomasz Wójcik",
                artworkId = 108,
                artworkTitle = "Miejski pejzaż nocą",
                artworkImage = null,
                quantity = 1,
                unitPrice = 3200.00,
                totalAmount = 3200.00,
                status = "DELIVERED",
                orderDate = "05.03.2026",
                paymentMethod = "Przelew bankowy",
                paymentStatus = "PAID",
                shippingAddress = "al. Solidarności 100",
                shippingCity = "Łódź",
                shippingPostalCode = "90-001",
                shippingCountry = "Polska",
                trackingNumber = "PL444555666",
                estimatedDelivery = "12.03.2026",
                actualDelivery = "11.03.2026",
                notes = null
            ),
            OrderInfo(
                id = 9,
                orderNumber = "ORD-2026-001242",
                buyerId = 4,
                buyerName = "Piotr Kamiński",
                buyerEmail = "piotr.kaminski@example.com",
                sellerId = 8,
                sellerName = "Magdalena Zielińska",
                artworkId = 109,
                artworkTitle = "Kwiatowy ogród",
                artworkImage = null,
                quantity = 1,
                unitPrice = 1500.00,
                totalAmount = 1500.00,
                status = "PENDING",
                orderDate = "27.03.2026",
                paymentMethod = "Karta kredytowa",
                paymentStatus = "PENDING",
                shippingAddress = "ul. Parkowa 45",
                shippingCity = "Wrocław",
                shippingPostalCode = "50-001",
                shippingCountry = "Polska",
                trackingNumber = null,
                estimatedDelivery = "03.04.2026",
                actualDelivery = null,
                notes = null
            ),
            OrderInfo(
                id = 10,
                orderNumber = "ORD-2026-001243",
                buyerId = 6,
                buyerName = "Katarzyna Lewandowska",
                buyerEmail = "k.lewandowska@example.com",
                sellerId = 2,
                sellerName = "Anna Nowak",
                artworkId = 110,
                artworkTitle = "Minimalista",
                artworkImage = null,
                quantity = 1,
                unitPrice = 2100.00,
                totalAmount = 2100.00,
                status = "SHIPPED",
                orderDate = "20.03.2026",
                paymentMethod = "BLIK",
                paymentStatus = "PAID",
                shippingAddress = "ul. Leśna 12",
                shippingCity = "Poznań",
                shippingPostalCode = "60-001",
                shippingCountry = "Polska",
                trackingNumber = "PL111222333",
                estimatedDelivery = "27.03.2026",
                actualDelivery = null,
                notes = null
            )
        )
    }
    
    fun getMockCategories(): List<CategoryInfo> {
        return listOf(
            CategoryInfo(
                id = 1,
                name = "Malarstwo",
                description = "Wszystkie rodzaje dzieł malarskich - od olejnych po akwarele",
                slug = "malarstwo",
                parentId = null,
                parentName = null,
                isActive = true,
                artworkCount = 1245,
                createdDate = "01.01.2024",
                lastModified = "15.03.2026",
                displayOrder = 1,
                iconName = "palette",
                color = "#E91E63"
            ),
            CategoryInfo(
                id = 2,
                name = "Malarstwo olejne",
                description = "Klasyczne malarstwo olejne na płótnie",
                slug = "malarstwo-olejne",
                parentId = 1,
                parentName = "Malarstwo",
                isActive = true,
                artworkCount = 567,
                createdDate = "01.01.2024",
                lastModified = "10.03.2026",
                displayOrder = 1,
                iconName = "brush",
                color = "#E91E63"
            ),
            CategoryInfo(
                id = 3,
                name = "Akwarele",
                description = "Delikatne malarstwo akwarelowe",
                slug = "akwarele",
                parentId = 1,
                parentName = "Malarstwo",
                isActive = true,
                artworkCount = 234,
                createdDate = "01.01.2024",
                lastModified = "08.03.2026",
                displayOrder = 2,
                iconName = "water_drop",
                color = "#2196F3"
            ),
            CategoryInfo(
                id = 4,
                name = "Malarstwo akrylowe",
                description = "Nowoczesne malarstwo akrylowe",
                slug = "malarstwo-akrylowe",
                parentId = 1,
                parentName = "Malarstwo",
                isActive = true,
                artworkCount = 444,
                createdDate = "01.01.2024",
                lastModified = "20.03.2026",
                displayOrder = 3,
                iconName = "brush",
                color = "#FF5722"
            ),
            CategoryInfo(
                id = 5,
                name = "Rzeźba",
                description = "Trójwymiarowe dzieła sztuki - od klasycznych po nowoczesne",
                slug = "rzezba",
                parentId = null,
                parentName = null,
                isActive = true,
                artworkCount = 156,
                createdDate = "01.01.2024",
                lastModified = "25.03.2026",
                displayOrder = 2,
                iconName = "sculpture",
                color = "#795548"
            ),
            CategoryInfo(
                id = 6,
                name = "Rzeźba kamienna",
                description = "Klasyczne rzeźby z kamienia i marmuru",
                slug = "rzezba-kamienna",
                parentId = 5,
                parentName = "Rzeźba",
                isActive = true,
                artworkCount = 45,
                createdDate = "01.01.2024",
                lastModified = "22.03.2026",
                displayOrder = 1,
                iconName = "architecture",
                color = "#795548"
            ),
            CategoryInfo(
                id = 7,
                name = "Rzeźba metalowa",
                description = "Nowoczesne rzeźby z różnych metali",
                slug = "rzezba-metalowa",
                parentId = 5,
                parentName = "Rzeźba",
                isActive = true,
                artworkCount = 78,
                createdDate = "01.01.2024",
                lastModified = "18.03.2026",
                displayOrder = 2,
                iconName = "precision_manufacturing",
                color = "#607D8B"
            ),
            CategoryInfo(
                id = 8,
                name = "Fotografia",
                description = "Fotografia artystyczna i dokumentalna",
                slug = "fotografia",
                parentId = null,
                parentName = null,
                isActive = true,
                artworkCount = 789,
                createdDate = "01.01.2024",
                lastModified = "26.03.2026",
                displayOrder = 3,
                iconName = "camera_alt",
                color = "#9C27B0"
            ),
            CategoryInfo(
                id = 9,
                name = "Fotografia portretowa",
                description = "Profesjonalne portrety i sesje zdjęciowe",
                slug = "fotografia-portretowa",
                parentId = 8,
                parentName = "Fotografia",
                isActive = true,
                artworkCount = 345,
                createdDate = "01.01.2024",
                lastModified = "24.03.2026",
                displayOrder = 1,
                iconName = "portrait",
                color = "#9C27B0"
            ),
            CategoryInfo(
                id = 10,
                name = "Sztuka współczesna",
                description = "Nowoczesne i eksperymentalne formy sztuki",
                slug = "sztuka-wspolczesna",
                parentId = null,
                parentName = null,
                isActive = true,
                artworkCount = 234,
                createdDate = "01.01.2024",
                lastModified = "27.03.2026",
                displayOrder = 4,
                iconName = "auto_fix_high",
                color = "#FF9800"
            ),
            CategoryInfo(
                id = 11,
                name = "Grafika cyfrowa",
                description = "Sztuka cyfrowa i ilustracje komputerowe",
                slug = "grafika-cyfrowa",
                parentId = 10,
                parentName = "Sztuka współczesna",
                isActive = true,
                artworkCount = 123,
                createdDate = "01.01.2024",
                lastModified = "26.03.2026",
                displayOrder = 1,
                iconName = "computer",
                color = "#FF9800"
            ),
            CategoryInfo(
                id = 12,
                name = "Rysunek",
                description = "Tradycyjne rysunki ołówkiem, węglem i innymi technikami",
                slug = "rysunek",
                parentId = null,
                parentName = null,
                isActive = true,
                artworkCount = 445,
                createdDate = "01.01.2024",
                lastModified = "23.03.2026",
                displayOrder = 5,
                iconName = "draw",
                color = "#4CAF50"
            ),
            CategoryInfo(
                id = 13,
                name = "Antyki",
                description = "Historyczne dzieła sztuki i przedmioty kolekcjonerskie",
                slug = "antyki",
                parentId = null,
                parentName = null,
                isActive = false,
                artworkCount = 23,
                createdDate = "01.01.2024",
                lastModified = "10.02.2026",
                displayOrder = 6,
                iconName = "museum",
                color = "#8BC34A"
            )
        )
    }
}
