POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "username": "nowy_user",
  "firstName": "Adam",
  "lastName": "Nowak",
  "email": "adam@wp.pl",
  "password": "moje_haslo123"
}