spring.application.name=backend

# Nazwa bazy, która przed chwila stworzyles
spring.datasource.url=jdbc:postgresql://localhost:5432/artsphere_db
spring.datasource.username=postgres
spring.datasource.password=student

# Hibernate - nie zmieniaj tabel automatycznie, uzyjemy naszych skryptow .sql
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# To sprawi, ?e Spring Boot przy starcie uruchomi schema.sql i data.sql
spring.sql.init.mode=always