spring.application.name=backend

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/artsphere_db
spring.datasource.username=postgres
spring.datasource.password=student

# Hibernate and SQL init
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.sql.init.mode=always

# Static resources
spring.web.resources.static-locations=classpath:/static/